name: lindhe-cloudflare-ddns
base: core18
version: '1.1.0'
summary: A DDNS client for Cloudflare DNS
description: |
  I made this script to be run as a cronjob that updates my DNS whenever the
  static IP changes.
# grade: stable
grade: devel
# confinement: strict
confinement: devmode

parts:
  lindhe-cloudflare-ddns:
    build-packages:
      - distro-info
      - cloud-init
    stage-packages:
      #- cloud-init
      - libatm1
    plugin: python
    python-version: python3
    #requirements:
    #  - ./requirements.txt
    source: .

apps:
  lindhe-cloudflare-ddns:
    command: bin/update_dns_record.py
