name: lindhe-cloudflare-ddns
base: core18
version: '0.1.0'
summary: A DDNS client for Cloudflare DNS
description: |
  I made this script to be run as a cronjob that updates my DNS whenever the
  static IP changes.
grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
